import os
from Modules.colors import cyan, green, red, yellow, bold

PYTHON_GITIGNORE = """__pycache__/
*.py[cod]
*$py.class
venv/
.venv/
env/
.env
.idea/
.vscode/
dist/
build/
*.egg-info/
.pytest_cache/
"""

CPP_GITIGNORE = """bin/
build/
*.o
*.obj
*.exe
*.out
.vscode/
.idea/
"""

DS_GITIGNORE = """__pycache__/
*.py[cod]
venv/
.venv/
.env
.ipynb_checkpoints/
data/raw/*
!data/raw/.gitkeep
models/*.pkl
models/*.pt
models/*.onnx
"""

def create_file(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content.strip() + "\n")

# --- Scaffolding Handlers ---

def scaffold_python(project_dir, project_name):
    create_file(os.path.join(project_dir, "src", "__init__.py"), "")
    create_file(os.path.join(project_dir, "src", "main.py"), f'''def main():
    print("Welcome to {project_name}!")

if __name__ == "__main__":
    main()
''')
    create_file(os.path.join(project_dir, "tests", "__init__.py"), "")
    create_file(os.path.join(project_dir, "tests", "test_main.py"), '''def test_example():
    assert 1 + 1 == 2
''')
    create_file(os.path.join(project_dir, "requirements.txt"), "# Add your pip dependencies here\n")
    create_file(os.path.join(project_dir, ".gitignore"), PYTHON_GITIGNORE)
    create_file(os.path.join(project_dir, "README.md"), f"# {project_name}\n\nInitialized with TermKit.\n\n## Running\n```bash\npython src/main.py\n```\n")

def scaffold_web(project_dir, project_name):
    html = f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{project_name}</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <div class="container">
        <h1>Welcome to {project_name}</h1>
        <p>A modern frontend project generated by TermKit.</p>
        <button id="btn">Click Me</button>
    </div>
    <script src="app.js"></script>
</body>
</html>
'''
    css = '''* { margin: 0; padding: 0; box-sizing: border-box; }
body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    background-color: #0f172a;
    color: #f8fafc;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
}
.container {
    text-align: center;
    padding: 2.5rem;
    background: #1e293b;
    border-radius: 12px;
    box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.4);
}
h1 { color: #38bdf8; margin-bottom: 1rem; }
button {
    margin-top: 1.5rem;
    padding: 0.75rem 1.5rem;
    background: #38bdf8;
    color: #0f172a;
    font-weight: bold;
    border: none;
    border-radius: 8px;
    cursor: pointer;
    transition: background 0.2s;
}
button:hover { background: #0284c7; }
'''
    js = '''document.addEventListener("DOMContentLoaded", () => {
    const btn = document.getElementById("btn");
    btn.addEventListener("click", () => {
        alert("Hello from TermKit Web Starter!");
    });
});
'''
    create_file(os.path.join(project_dir, "index.html"), html)
    create_file(os.path.join(project_dir, "style.css"), css)
    create_file(os.path.join(project_dir, "app.js"), js)
    create_file(os.path.join(project_dir, "README.md"), f"# {project_name}\n\nOpen `index.html` in your web browser.\n")

def scaffold_api(project_dir, project_name):
    main_code = '''from flask import Flask, jsonify

app = Flask(__name__)

@app.route("/")
def home():
    return jsonify({"status": "online", "service": "Flask API", "version": "1.0.0"})

@app.route("/health")
def health():
    return jsonify({"health": "ok"})

if __name__ == "__main__":
    app.run(debug=True, port=5000)
'''
    create_file(os.path.join(project_dir, "main.py"), main_code)
    create_file(os.path.join(project_dir, "requirements.txt"), "flask>=3.0.0\n")
    create_file(os.path.join(project_dir, ".gitignore"), PYTHON_GITIGNORE)
    create_file(os.path.join(project_dir, "README.md"), f"# {project_name} (Flask API)\n\n```bash\npip install -r requirements.txt\npython main.py\n```\n")

def scaffold_fastapi(project_dir, project_name):
    main_code = '''from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel

app = FastAPI(title="''' + project_name + '''", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class Item(BaseModel):
    name: str
    price: float
    description: str = None

@app.get("/")
def root():
    return {"status": "online", "message": "FastAPI service is running"}

@app.get("/health")
def health():
    return {"health": "healthy"}

@app.post("/items")
def create_item(item: Item):
    return {"message": "Item created successfully", "item": item}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
'''
    create_file(os.path.join(project_dir, "main.py"), main_code)
    create_file(os.path.join(project_dir, "requirements.txt"), "fastapi>=0.110.0\nuvicorn[standard]>=0.28.0\npydantic>=2.0.0\n")
    create_file(os.path.join(project_dir, ".gitignore"), PYTHON_GITIGNORE)
    create_file(os.path.join(project_dir, "README.md"), f"# {project_name} (FastAPI)\n\n## Running\n```bash\npip install -r requirements.txt\nuvicorn main:app --reload\n```\nInteractive Docs: Visit `http://localhost:8000/docs`\n")

def scaffold_data_science(project_dir, project_name):
    create_file(os.path.join(project_dir, "data", "raw", ".gitkeep"), "")
    create_file(os.path.join(project_dir, "data", "processed", ".gitkeep"), "")
    create_file(os.path.join(project_dir, "models", ".gitkeep"), "")
    create_file(os.path.join(project_dir, "src", "__init__.py"), "")
    create_file(os.path.join(project_dir, "src", "utils.py"), '''import pandas as pd
import numpy as np

def load_data(filepath):
    """Utility to load dataset safely."""
    return pd.read_csv(filepath)
''')
    create_file(os.path.join(project_dir, "notebooks", "eda_starter.py"), '''# EDA Starter Script / Notebook
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Data science workspace initialized successfully!")
''')
    create_file(os.path.join(project_dir, "requirements.txt"), "pandas>=2.0.0\nnumpy>=1.24.0\nmatplotlib>=3.7.0\nseaborn>=0.12.0\nscikit-learn>=1.3.0\njupyter>=1.0.0\n")
    create_file(os.path.join(project_dir, ".gitignore"), DS_GITIGNORE)
    create_file(os.path.join(project_dir, "README.md"), f"# {project_name} (Data Science & ML)\n\n## Setup\n```bash\npip install -r requirements.txt\njupyter notebook\n```\n")

def scaffold_cli(project_dir, project_name):
    cli_code = f'''import argparse
import sys

def main():
    parser = argparse.ArgumentParser(description="{project_name} CLI Tool")
    parser.add_argument("-v", "--version", action="version", version="{project_name} 1.0.0")
    
    subparsers = parser.add_subparsers(dest="command", help="Available subcommands")
    
    hello_parser = subparsers.add_parser("greet", help="Greet the user")
    hello_parser.add_argument("name", nargs="?", default="World", help="Name to greet")
    
    args = parser.parse_args()
    
    if args.command == "greet":
        print(f"Hello, {{args.name}}!")
    else:
        parser.print_help()

if __name__ == "__main__":
    main()
'''
    setup_code = f'''from setuptools import setup, find_packages

setup(
    name="{project_name}",
    version="1.0.0",
    packages=find_packages(),
    entry_points={{
        "console_scripts": [
            "{project_name}=src.cli:main",
        ],
    }},
)
'''
    create_file(os.path.join(project_dir, "src", "__init__.py"), "")
    create_file(os.path.join(project_dir, "src", "cli.py"), cli_code)
    create_file(os.path.join(project_dir, "setup.py"), setup_code)
    create_file(os.path.join(project_dir, "requirements.txt"), "# Core CLI uses standard library\n")
    create_file(os.path.join(project_dir, ".gitignore"), PYTHON_GITIGNORE)
    create_file(os.path.join(project_dir, "README.md"), f"# {project_name} CLI\n\n```bash\npython src/cli.py greet Alice\n```\n")

def scaffold_bot(project_dir, project_name):
    bot_code = '''import asyncio
import os

print("Starting bot...")

async def handle_command(command, args):
    if command == "ping":
        return "Pong! Bot latency is healthy."
    elif command == "echo":
        return " ".join(args)
    return f"Unknown command: {command}"

async def main():
    print("Bot is listening for events... (Press Ctrl+C to stop)")
    while True:
        await asyncio.sleep(1)

if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        print("\\nBot stopped.")
'''
    create_file(os.path.join(project_dir, "bot.py"), bot_code)
    create_file(os.path.join(project_dir, ".env.example"), "BOT_TOKEN=your_token_here\nPREFIX=!\n")
    create_file(os.path.join(project_dir, "requirements.txt"), "python-dotenv>=1.0.0\n")
    create_file(os.path.join(project_dir, ".gitignore"), PYTHON_GITIGNORE)
    create_file(os.path.join(project_dir, "README.md"), f"# {project_name} Bot\n\n```bash\ncp .env.example .env\npython bot.py\n```\n")

def scaffold_fullstack(project_dir, project_name):
    server_code = '''from flask import Flask, jsonify, send_from_directory
import os

app = Flask(__name__, static_folder="../frontend")

@app.route("/api/status")
def status():
    return jsonify({"status": "healthy", "service": "Fullstack Backend API", "version": "1.0.0"})

@app.route("/")
def index():
    return send_from_directory(app.static_folder, "index.html")

@app.route("/<path:path>")
def static_files(path):
    return send_from_directory(app.static_folder, path)

if __name__ == "__main__":
    app.run(debug=True, port=5000)
'''
    html_code = f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{project_name} Fullstack</title>
    <style>
        body {{ font-family: sans-serif; background: #0f172a; color: #f8fafc; text-align: center; padding: 3rem; }}
        .card {{ background: #1e293b; display: inline-block; padding: 2rem; border-radius: 12px; }}
        #status {{ color: #38bdf8; font-weight: bold; margin-top: 1rem; }}
    </style>
</head>
<body>
    <div class="card">
        <h1>{project_name}</h1>
        <p>Fullstack App connected to Flask API.</p>
        <div id="status">Connecting to backend...</div>
    </div>
    <script>
        fetch('/api/status')
            .then(res => res.json())
            .then(data => {{ document.getElementById('status').innerText = 'Backend: ' + data.status + ' (v' + data.version + ')'; }})
            .catch(err => {{ document.getElementById('status').innerText = 'Backend connection error'; }});
    </script>
</body>
</html>
'''
    create_file(os.path.join(project_dir, "backend", "server.py"), server_code)
    create_file(os.path.join(project_dir, "frontend", "index.html"), html_code)
    create_file(os.path.join(project_dir, "requirements.txt"), "flask>=3.0.0\n")
    create_file(os.path.join(project_dir, ".gitignore"), PYTHON_GITIGNORE)
    create_file(os.path.join(project_dir, "README.md"), f"# {project_name} Fullstack\n\n```bash\npip install -r requirements.txt\npython backend/server.py\n```\nVisit `http://localhost:5000` in your browser.\n")

def scaffold_cpp(project_dir, project_name):
    main_c = '''#include <stdio.h>
#include "utils.h"

int main() {
    printf("Welcome to ''' + project_name + '''!\\n");
    print_greeting();
    return 0;
}
'''
    utils_h = '''#ifndef UTILS_H
#define UTILS_H

void print_greeting();

#endif
'''
    utils_c = '''#include <stdio.h>
#include "utils.h"

void print_greeting() {
    printf("Compiled with Makefile successfully!\\n");
}
'''
    makefile = '''CC = gcc
CFLAGS = -Wall -Iinclude
SRC = src/main.c src/utils.c
OBJ = $(SRC:.c=.o)
TARGET = bin/app

all: $(TARGET)

$(TARGET): $(OBJ)
\tmkdir -p bin
\t$(CC) $(OBJ) -o $(TARGET)

src/%.o: src/%.c
\t$(CC) $(CFLAGS) -c $< -o $@

clean:
\trm -f src/*.o bin/*

run: $(TARGET)
\t./$(TARGET)
'''
    create_file(os.path.join(project_dir, "src", "main.c"), main_c)
    create_file(os.path.join(project_dir, "src", "utils.c"), utils_c)
    create_file(os.path.join(project_dir, "include", "utils.h"), utils_h)
    create_file(os.path.join(project_dir, "Makefile"), makefile)
    create_file(os.path.join(project_dir, ".gitignore"), CPP_GITIGNORE)
    create_file(os.path.join(project_dir, "README.md"), f"# {project_name} (C/C++)\n\n```bash\nmake\nmake run\n```\n")

# --- Template Registry ---

TEMPLATES = {
    "python":       ("Standard Python package (src, tests, requirements.txt, .gitignore)", scaffold_python, "Python & Core"),
    "web":          ("Modern HTML5, dark-themed CSS3 & JavaScript starter", scaffold_web, "Web & Frontend"),
    "api":          ("Lightweight Flask REST API with / and /health routes", scaffold_api, "Web & APIs"),
    "fastapi":      ("High-performance async FastAPI with Pydantic & Swagger docs", scaffold_fastapi, "Web & APIs"),
    "data-science": ("Complete ML & Data Science workspace (data/, models/, notebooks/)", scaffold_data_science, "Data Science & AI"),
    "cli":          ("Python CLI app boilerplate with argparse, subcommands & setup.py", scaffold_cli, "Tools & Systems"),
    "bot":          ("Async Python bot starter with command dispatcher & .env", scaffold_bot, "Tools & Systems"),
    "fullstack":    ("Unified web app with frontend/ UI & backend/ REST server", scaffold_fullstack, "Fullstack"),
    "c-cpp":        ("Modern C/C++ project with Makefile, include/, and src/", scaffold_cpp, "Tools & Systems"),
}

def list_templates():
    print(f"\n{bold('Available Project Blueprints:')}")
    print("  " + "=" * 70)
    
    categories = {}
    for name, (desc, _, cat) in TEMPLATES.items():
        categories.setdefault(cat, []).append((name, desc))

    for cat, items in categories.items():
        print(f"\n  {yellow(bold(cat))}:")
        for name, desc in items:
            print(f"    {cyan(name):<15} - {desc}")

    print("\n  " + "=" * 70)
    print(f"\nUsage: {cyan('init <template> <project_name>')}")
    print(f"Example: {cyan('init fastapi my_api')}")
    print(f"Example: {cyan('init data-science customer_churn')}\n")

def interactive_init():
    print(f"\n{cyan(bold('--- TermKit Project Scaffolding Wizard ---'))}")
    print("Choose a project blueprint:\n")
    
    template_list = list(TEMPLATES.keys())
    for i, name in enumerate(template_list, 1):
        desc, _, cat = TEMPLATES[name]
        print(f"  {cyan(str(i).rjust(2))}) {bold(name):<16} [{cat}] - {desc}")

    print()
    choice = input(f"{bold('Enter template number (1-9) or name [or Enter to cancel]: ')}").strip()
    if not choice:
        print(yellow("Cancelled.\n"))
        return

    selected_template = None
    if choice.isdigit() and 1 <= int(choice) <= len(template_list):
        selected_template = template_list[int(choice) - 1]
    elif choice.lower() in TEMPLATES:
        selected_template = choice.lower()
    else:
        print(red(f"Invalid selection: '{choice}'\n"))
        return

    project_name = input(f"{bold('Enter project folder name: ')}").strip()
    if not project_name:
        print(red("Error: Project name cannot be empty.\n"))
        return

    init_command([selected_template, project_name])

def help_command():
    print(f"\n{bold('Project Scaffolder (init):')}")
    print(f"  {cyan('init <template> <project_name>'):<32} - Create a new project blueprint")
    print(f"  {cyan('init list'):<32} - View all 9 available project templates")
    print(f"  {cyan('init'):<32} - Launch interactive project creation wizard")
    print(f"  {cyan('init help'):<32} - Show this help menu\n")

def init_command(arguments):
    if len(arguments) == 0:
        interactive_init()
        return

    if arguments[0].lower() == "help":
        help_command()
        return

    if arguments[0].lower() == "list":
        list_templates()
        return

    if len(arguments) < 2:
        print(f"{yellow('Usage:')} init <template> <project_name> (e.g. init fastapi my_api)")
        print(f"Type '{cyan('init list')}' to see all templates or '{cyan('init')}' for interactive wizard.\n")
        return

    template = arguments[0].lower()
    project_name = arguments[1]

    if template not in TEMPLATES:
        print(f"{red('Error:')} Unknown template '{template}'. Type '{cyan('init list')}' for available templates.")
        return

    if os.path.exists(project_name):
        print(f"{red('Error:')} A folder or file named '{project_name}' already exists in this directory.\n")
        return

    desc, scaffold_func, cat = TEMPLATES[template]
    print(f"\nInitializing {cyan(bold(template))} [{cat}] project in {bold(project_name)}...")

    try:
        scaffold_func(project_name, project_name)
        print(green(f"Successfully generated {bold(project_name)}!"))
        print(f"  --> Run '{cyan(f'files list {project_name}')}' to explore your new blueprint.\n")
    except Exception as e:
        print(f"{red('Failed to scaffold project:')} {e}\n")
